### ISSUE TITLE
Old Version of Wheel being Sourced

### ISSUE THREAD

**Issue by zanes2016** [benley/bazel_rules_pex#23]
I'm seeing the following error:

> File "/home/.cache/bazel/_bazel_zanes/ea59e07677eec0e868edc628a8df6a9d/execroot/repo/.pex/interpreters/CPython-3.4.3/wheel-0.25.0-py3.4.egg/wheel/bdist_wheel.py", line 229, in run
>   File "/home/.cache/bazel/_bazel_zanes/ea59e07677eec0e868edc628a8df6a9d/execroot/repo/.pex/interpreters/CPython-3.4.3/wheel-0.25.0-py3.4.egg/wheel/bdist_wheel.py", line 394, in egg2dist
>   File "/home/.cache/bazel/_bazel_zanes/ea59e07677eec0e868edc628a8df6a9d/execroot/repo/.pex/interpreters/CPython-3.4.3/wheel-0.25.0-py3.4.egg/wheel/metadata.py", line 194, in pkginfo_to_dict
> TypeError: unorderable types: EntryPoint() < EntryPoint()

This python TypeError was fixed in wheel 0.26.0: https://bitbucket.org/pypa/wheel/issues/148/unorderable-types-error-for-python-3

However, you can see that wheel-0.25.0 is being used. Any idea why this old version of wheel is being used to compile this source?

For reference, here's my pex BUILD file. I'm using python3.4 on Ubuntu 14.04 with Bazel 0.3.1.

pex_binary(
  name='app',
  main = 'app.py',  
  srcs= [
    'app.py' 
  ],
  deps = [
    '//app/controllers'
  ],
  interpreter = 'python3.4',
  reqs = ['cython', 'numpy', 'pandas'],
  eggs = [
    '//third_party/python/ppcapp'
  ],
)

**Comment by evanj** [comment]
I think this issue can probably be closed. Commit 8037dfcd2f4a715928df9028c56ac8379a683bef updated this to wheel 0.29 which is the latest that Pex specifies: `'wheel>=0.26.0,<0.30.0'`; See 
https://github.com/pantsbuild/pex/blob/master/pex/version.py
