### ISSUE TITLE
Could you please add a license to your project.

### ISSUE THREAD

**Issue by srikalyan** [benley/bazel_rules_pex#34]
Could you please add a license to your project (MIT if possible) so that I can submit my PR that considers imports?

**Comment by benley** [comment]
Totally.  The origins of this code are under the Apache-2.0 license (see the license header in [pex_rules.bzl](https://github.com/benley/bazel_rules_pex/blob/master/pex/pex_rules.bzl)), so I don't think I can legally change it to MIT.  Hopefully Apache license is okay for you?

**Comment by srikalyan** [comment]
cool that works I guess.
