### ISSUE TITLE
Virtualenv data glob is too aggressive

### ISSUE THREAD

**Issue by marczych** [benley/bazel_rules_pex#39]
I've been noticing that pex rules end up rebuilding unnecessarily. I dug into it and found that building `@io_bazel_rules_pex//pex:pex_wrapper` builds `@virtualenv//:virtualenv`. However, immediately after that, building the pex wrapper with `--check_up_to_date` fails because it claims that the source manifest for virtualenv is out of date. It then stabilizes after building it a second time.

It turns out that running the virtualenv binary sticks a `virtualenv.pyc` next to `virtualenv.py` and thus invalidates [this aggressive glob](https://github.com/benley/bazel_rules_pex/blob/a000d98c8dd406d032ae4fc6756398599eed0bfc/pex/pex_rules.bzl#L506).

I fixed it by explicitly excluding that pyc file but I'm hoping that there is a better fix to not use a glob and only include the files that are needed.

**Comment by benley** [comment]
Nice catch, thank you! I have a feeling that a more specific glob or set of globs will be easy enough to do.

**Comment by evanj** [comment]
Oh, hey, this might be the same bug I found in PR #57 which has since been merged!

**Comment by benley** [comment]
Sure enough!

**Comment by marczych** [comment]
👍
