### ISSUE TITLE
setting interpreter attribute isn't enough 

### ISSUE THREAD

**Issue by mouadino** [benley/bazel_rules_pex#44]
### Summary

This is similar to the bug here https://github.com/pantsbuild/pants/issues/4490, sadly setting `interpreter` attribute in Pex's rules to `python3.6` isn't enough, but you also you need to have `/usr/bin/env python` and `pip` pointing to Python 3.6 in the host machine.

### Open Questions

I was wondering, although I am not sure if this is the right place to ask, why is python rules not using sandbox like example Golang, there you can specify the go version in the WORKSPACE and Bazel downloads the specific Golang environment in a sandbox and use this later, instead of relying on host system, in contrast, python rules rely on the host system which makes setting up working with Bazel and Python too cumbersome.

**Comment by benley** [comment]
I would love to build using a sandboxed Python that Bazel manages, but as far as I know there are no standard binary distributions of Python available for Linux.  We could compile cpython on demand, but that itself is non-trivial due to the number of things it can optionally depend on and the different ways it can be configured.  If you know of better options I would be happy to hear about them!

**Comment by mouadino** [comment]
For the sandboxing, I know [pyenv](https://github.com/pyenv/pyenv) does that although I am unsure of the details, maybe using pyenv directly can be an option? 

For the short term, I suggest adding a note about this caveat in the README to avoid other ppl to fall in the same trap.

**Comment by mouadino** [comment]
This just became very hairy, since I am also using https://github.com/bazelbuild/rules_docker which works only with Python 2 and fails if `/urs/bin/env python` point to Python 3, works trying argument like `--force_python=py2` break Pex as mentioned above, chicken and egg problem :( 

Good news is that I was able to make it work, check please this PR https://github.com/benley/bazel_rules_pex/pull/45

I will also still love to see the sandboxing for python working :)
